"""Rename User to Provider and add patient fields

Revision ID: 5293bc877346
Revises: 722b9ad7b44a
Create Date: 2024-12-17 11:58:29.458176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5293bc877346'
down_revision = '722b9ad7b44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('test_name', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_devicedata_patient', 'patient', ['patient_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_devicedata_patient', type_='foreignkey')
        batch_op.drop_column('test_name')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
