"""empty message

Revision ID: 722b9ad7b44a
Revises: cbeb1fe3d7fa
Create Date: 2024-11-24 12:37:36.786007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722b9ad7b44a'
down_revision = 'cbeb1fe3d7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ow1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ow2', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.drop_column('ow2')
        batch_op.drop_column('ow1')

    # ### end Alembic commands ###
