"""changing name of column in DeviceData

Revision ID: cbeb1fe3d7fa
Revises: 
Create Date: 2024-11-23 16:05:35.022466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbeb1fe3d7fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test2')
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_timestamp', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('request_timestamp')

    op.create_table('test2',
    comment='asdf'
    )
    # ### end Alembic commands ###
